python int4_quzo_perturb.py \
  --model_name Qwen/Qwen2.5-3B-Instruct-GPTQ-Int8 \
  --sigma 0.001 \
  --alpha 0.0001 \
  --population_size 50 \
  --num_engines 4 \
  --num_iterations 350 \
  --experiment_dir experiment_quant/int8-3B-seed-replay \
  --discrete_step_gain 1.0 \
  --cuda_devices 4,5,6,7 \
  --global_seed 10086 \
  --mirror_sampling \
  --verbose